# Generated by Django 5.1.6 on 2025-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
